#!/usr/bin/env python3

import argparse
from collections import defaultdict
import shutil
import sys
import unittest
from pathlib import Path

this_file = Path(__file__).resolve()
lib_dir = this_file.parents[1]/'lib'
tests_dir = this_file.parent/'tests'

# Setup our paths to the pavilion libraries.
sys.path.insert(0, str(lib_dir))


def _list_tests(suite):
    """Return a list of tuples of (suite_name, test_name)"""

    tests = []

    if isinstance(suite, unittest.TestSuite):
        for subsuite in suite:
            tests.extend(_list_tests(subsuite))

        return tests

    by_suite = {}

    suite_name = suite.__class__.__name__
    return [(suite_name, suite._testMethodName)]

def list_tests(suite):
    
    tests = _list_tests(suite)

    by_suite = defaultdict(list)

    for suite_name, test_name in tests:
        if test_name.startswith('test_'):
            test_name = test_name[len('test_'):]
        by_suite[suite_name].append(test_name)

    for suite_name in sorted(by_suite.keys()):
        print('{}:'.format(suite_name))
        for test_name in sorted(by_suite[suite_name]):
            print('  {}'.format(test_name))


def main():
    from pavilion.unittest import PavTestCase, ColorResult, BetterRunner
    from pavilion import log_setup

    config = PavTestCase.TEST_DATA_ROOT/'pav_config_dir'/'pavilion.yaml'
    if not config.exists():
        print("\nERROR")
        print("Could not find a config file at '{}'".format(config))
        print("To run tests, this file must be created.")
        print("It may be blank, or may contain proxy info.")
        sys.exit(1)

    parser = argparse.ArgumentParser(
        usage="This runs all the tests in the tests/ directory. For a python " 
              "file to be recognized as a test suite, it must end in "
              "'_tests.py'. All other files are ignored")
    parser.add_argument('-l', '--list', action='store_true', 
                        help="List the tests, but don't run them.")
    parser.add_argument('-s', '--skip', action='append', default=[],
                        help="Skip tests matching the given glob pattern. The "
                             "'test_' prefix is removed from the name for this "
                             "check.")
    parser.add_argument('-o', '--only', action='append', default=[],
                        help="Only run tests matching the given glob pattern. "
                             "The 'test_' prefix is removed from the name "
                             "for this check.")
    parser.add_argument('-v', '--verbose', action='store_true', default=False,
                        help="Print all log output to stderr.")
    parser.add_argument('-q', '--quiet', action='store_true', default=False,
                        help="Silence.")
    parser.add_argument('-C', '--no-clear', action='store_true', default=False,
                        help="Don't clear the working directory before "
                             "running.")
    args = parser.parse_args(sys.argv[1:])

    if args.skip:
        PavTestCase.set_skip(args.skip)
    if args.only:
        PavTestCase.set_only(args.only)

    working_dir = this_file.parent/'working_dir'
    if not args.list and not args.no_clear and working_dir.exists():
        print("Clearing out the working directory from prior unit test runs.")
        shutil.rmtree(working_dir.as_posix(), ignore_errors=False)

        log_setup.setup_loggers(PavTestCase().pav_cfg, verbose=args.verbose)

    verbosity = 0 if args.quiet else 2

    loader = unittest.TestLoader()
    suite = loader.discover(tests_dir.as_posix(), pattern='*_tests.py')

    if args.list:
        list_tests(suite)
        return 0
    else:
        runner = BetterRunner(resultclass=ColorResult, verbosity=verbosity)
        result = runner.run(suite)
        return len(result.errors) + len(result.failures)


PROFILE = False


if __name__ == '__main__':

    if not PROFILE:
        sys.exit(main())
    else:
        import cProfile
        import pstats
        stats_file = '/tmp/pav_unittest_stats'
        cProfile.run('sys.exit(main())', stats_file)
        stats = pstats.Stats(stats_file)
        print('cumulative')
        stats.sort_stats('cumulative').print_stats(20)
        print('time')
        stats.sort_stats('time').print_stats(20)

