site_name: Pavilion
copyright: © Copyright Triad National Security, LLC. All Rights Reserved.
theme:
    name: readthedocs
nav:
    - Home: index.md
    - Development Guidelines: DevelopmentGuidelines.md 
    - Setup:
        - Installing Pavilion: install.md
        - Configuring Pavilion: config.md
    - Usage:
        - Pavilion Basic Usage: basic.md
        - Pavilion Advanced Usage: advanced.md 
    - Writing Tests:
        - Basics: tests/basics.md
        - Building: tests/build.md
        - Running: tests/run.md
        - Environment: tests/env.md
        - Scheduling: index.md
        - Results: tests/results.md
        - Variables: tests/variables.md
        - Permutations: index.md
    - Plugins and Customization:
        - Basics: plugins/basics.md
        - System Variables: plugins/sys_vars.md
        - Module Wrappers: plugins/module_wrappers.md
        - Result Parsers: index.md
        - Schedulers: index.md
        - Commands: plugins/commands.md
    - License: LICENSE.md
