#!/bin/tcsh


# set up internationalization 
# set all locale categories to ISO C 
setenv LC_ALL C

set nodes = `${PVINSTALL}/PAV/scripts/checkjob_getNodeList ${PV_JOBID}`
echo "$nodes" | gawk '{ for ( i=1 ; i <= NF ; i++ ) print $i }'

echo "$nodes"

# End of script
exit

