#!/usr/bin/perl -w

#  ###################################################################
#
#  Disclaimer and Notice of Copyright 
#  ==================================
#
#  Copyright (c) 2015, Los Alamos National Security, LLC
#  All rights reserved.
#
#  Copyright 2015. Los Alamos National Security, LLC. 
#  This software was produced under U.S. Government contract 
#  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), 
#  which is operated by Los Alamos National Security, LLC for 
#  the U.S. Department of Energy. The U.S. Government has rights 
#  to use, reproduce, and distribute this software.  NEITHER 
#  THE GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES 
#  ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY 
#  FOR THE USE OF THIS SOFTWARE.  If software is modified to 
#  produce derivative works, such modified software should be 
#  clearly marked, so as not to confuse it with the version 
#  available from LANL.
#
#  Additionally, redistribution and use in source and binary 
#  forms, with or without modification, are permitted provided 
#  that the following conditions are met:
#  -  Redistributions of source code must retain the 
#     above copyright notice, this list of conditions 
#     and the following disclaimer. 
#  -  Redistributions in binary form must reproduce the 
#     above copyright notice, this list of conditions 
#     and the following disclaimer in the documentation 
#     and/or other materials provided with the distribution. 
#  -  Neither the name of Los Alamos National Security, LLC, 
#     Los Alamos National Laboratory, LANL, the U.S. Government, 
#     nor the names of its contributors may be used to endorse 
#     or promote products derived from this software without 
#     specific prior written permission.
#   
#  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC 
#  AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
#  IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR CONTRIBUTORS 
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
#  OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
#  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR 
#  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
#  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
#  OF SUCH DAMAGE.
#
#  ###################################################################


our %opts;
my (
	$tmp,$usage,$gname,$user,$userlist,@nada,$grplist,
	@stuff,$grp
   );

# # ------------------------------------------------------------------ # #


# get parameters from command line
use Getopt::Std;
$opts{g} = "";          # group name for which info is deisred
$opts{u} = "";          # user moniker for which info is desired
getopts("m:g:u:ht",\%opts);

if ( $opts{h} ) {	# print usage info
   $usage = <<EOF;
   Usage:  $0 [-g <group_name>] [-u <user_moniker>] [-h] [-t]
   -g option alone will list the monikers of the users who
      are members in the group "group_name".
   -u option alone will list the groups to which the user
      specified as "user_moniker" belongs.
   Including both -g and -u on the command line will return 
      1 if the user user_moniker belongs to group group_name, 
      and 0 otherwise.
   -h gives this help message
   -t means return the -g or -u list with a title line
EOF
   print "$usage\n";
   exit;
}

# indicate mode of functioning of this routine:

$user = "$opts{u}";
$user =~ s/\s//g;

$gname = "$opts{g}";
$gname =~ s/\s//g;


# # ------------------------------------------------------------------ # #

# get "gz" groups to which specified user belongs
if (( $opts{u} ) && (! $opts{g} )) {
   $grplist = `grep $user /etc/group | grep gz | awk -F: '{print \$1}' | xargs`;
   chop($grplist);
   if ( $opts{t} ) {
      print "User $user belongs to the following groups: \n\t$grplist\n";
   } else {
      print "$grplist\n";
   }
}

# get users in specified group
if (( $opts{g} ) && (! $opts{u} )) {
      $userlist = `grep $gname /etc/group`;
      if ( length("$userlist") > 1 ) {
         @nada = split ':',$userlist;
         $userlist = "$nada[$#nada]";
      }

   chop($userlist);
   if ( $opts{t} ) {
      print "Group $gname has the following members: \n\t$userlist\n";
   } else {
      print "$userlist\n";
   }
}

# return 0 or 1 to say if specified user belongs to specified group
if (( $opts{u} ) && ( $opts{g} )) {
      $userlist = `grep $gname /etc/group`;
      if ( $userlist =~ /$user/ ) {
          print "1";
      } else {
          print "0";
      }
}

exit;
