#!/usr/bin/perl -w

$| = 1;
(our $prog = $0) =~ s!.*/!!;

use POSIX qw(sysconf times);

die "usage: $prog <cmd>\n"
  unless(scalar(@ARGV));

our $ticks = POSIX::sysconf(&POSIX::_SC_CLK_TCK);
die "$prog: clock ticks undefined on this system!\n"
   unless (defined($ticks));

our ($r1,$u1,$s1,$cu1,$cs1) = POSIX::times;
system { $ARGV[0] } @ARGV; our $status = $? >> 8;
our ($r2,$u2,$s2,$cu2,$cs2) = POSIX::times;

printf "\nreal %7.2f\nuser %7.2f\nsys %7.2f\n",
   ($r2-$r1)/$ticks,                    # real seconds
   (($u2+$cu2)-($u1+$cu1))/$ticks,      # user seconds
   (($s2+$cs2)-($s1+$cs1))/$ticks;      # system seconds

exit $status;
