#!/usr/bin/perl

#  ###################################################################
#
#  Disclaimer and Notice of Copyright 
#  ==================================
#
#  Copyright (c) 2014, Los Alamos National Security, LLC
#  All rights reserved.
#
#  Copyright 2014. Los Alamos National Security, LLC. 
#  This software was produced under U.S. Government contract 
#  DE-AC52-06NA25396 for Los Alamos National Laboratory (LANL), 
#  which is operated by Los Alamos National Security, LLC for 
#  the U.S. Department of Energy. The U.S. Government has rights 
#  to use, reproduce, and distribute this software.  NEITHER 
#  THE GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC MAKES 
#  ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY 
#  FOR THE USE OF THIS SOFTWARE.  If software is modified to 
#  produce derivative works, such modified software should be 
#  clearly marked, so as not to confuse it with the version 
#  available from LANL.
#
#  Additionally, redistribution and use in source and binary 
#  forms, with or without modification, are permitted provided 
#  that the following conditions are met:
#  -  Redistributions of source code must retain the 
#     above copyright notice, this list of conditions 
#     and the following disclaimer. 
#  -  Redistributions in binary form must reproduce the 
#     above copyright notice, this list of conditions 
#     and the following disclaimer in the documentation 
#     and/or other materials provided with the distribution. 
#  -  Neither the name of Los Alamos National Security, LLC, 
#     Los Alamos National Laboratory, LANL, the U.S. Government, 
#     nor the names of its contributors may be used to endorse 
#     or promote products derived from this software without 
#     specific prior written permission.
#   
#  THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC 
#  AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
#  IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR CONTRIBUTORS 
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
#  OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
#  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR 
#  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
#  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
#  OF SUCH DAMAGE.
#
#  ###################################################################


#
# This script will transforms logfile trenddata "<td>" into a global CSV results file. 

use File::Basename;
use Pod::Usage;
use Getopt::Std;

(my $prog = $0) =~ s/.*\///;

my %attr =
(
   RaiseError => 0,
   PrintError => 0,
   AutoCommit => 1
);

use strict;

use Getopt::Std;
our %opt;
&getopts("dh:", \%opt);

  # print help if requested
  if ( $opt{h}) { usage(); exit; }

  my $jlf = $ENV{'PV_JOB_RESULTS_LOG'};
  chomp $jlf;
  my $ofd = $ENV{'PV_RESULT_ROOT'};
  chomp $ofd;

  # read from the logfile
  open( LOG, "<$jlf") or die "$prog: Failed to open job log file $jlf, $!\n";

  my $hdr = "";
  my $resrecord = "";
  our $date = "";
  our $time = "";
  our $edate = "";
  our $etime = "";
  my $tn = "";
  my $mn = "";
  my $pl = "";
  my $nl = "";
  my $nc = "";
  my $nn = "";
  my $sn = "";
  my $job_id = "";
  my $td_name;
  my $td_vals;
  my %td = ();
  my $td_val;
  my $td_units;
  my $td_list = "";
  my $results = "unknown";

  while( <LOG> ) {
#       print "DEBUGGING: input=$_\n";
#        chop( $_  );

      # extract target machine name
      if (/^<machine> /) {
        $mn = $';
        chomp $mn;
        next;
      }

      # extract target segment name
      if (/^<segName> /) {
        $sn = $';
        chomp $sn;
        next;
      }

      # extract test name
      if (/^<testName> /) {
        $tn = $';
        chomp $tn;
        next;
      }

      # extract PE (cores) name
      if (/^<npes> /) {
        $nc = $';
        chomp $nc;
        next;
      }

      # get job id to include in splunk data
      if ( /^<JobID> / ) {
	 $job_id = $';
         chomp $job_id;
	 next;
      } 

      # extract node list 
      if (/^<nodes> /) {
        $nl = $';
        chomp $nl;
        $nn++ while $nl =~ /\S+/g;
        $nl =~ s/\s+/,/g;
        next;
      }

      # extract the parameter list
      if (/^<params> /) {
        $pl = $';
        chomp $pl;
        $pl =~ s/\s+/__/g;
        next;
      }

      # get start time to use in splunk data 
      if( /^<start> / ) {
         my $start = $';
         chomp $start;
         ($date, $time) = split("T", $start); 
         $time =~ s/-.*//;
         next;
      }

      # get end time to use in splunk data 
      if( /^<end> / ) {
         my $end = $';
         chomp $end;
         ($edate, $etime) = split("T", $end); 
         $etime =~ s/-.*//;
         $edate =~ s/^\s+//;
         next;
      }

      # get results  
      # save the first pass, unless a fail then save the first one of those 
      if (/<result\w{0,1}>\s*(.+)/){
         my $tmpStr = $1;
         $tmpStr =~ s/[,:].+$//; # remove any text after pass/fail
         if ($results =~ /unknown/) {
           $results = $tmpStr;
         }
         if ( ($tmpStr =~ /fail/i) && ( $results !~ /fail/i) ) {
           $results = $tmpStr;
         }
         chomp $results;
         next;
      }

      # process test specific data types
      #
      # <td> standard trend data which is formatted as "name value [units]"
      #    is included with the common data in the output record.
      #

      if ( /<td>\s+(.*)/ ) {
        $td_name = "";
        $td_val = "";
        $td_units = "";

        my @td = split(" ", $1);
        $td_name = $td[0];
        $td_name =~ s/-/_/g; # no "-"s allowed in std. trend data
        $td_val = $td[1];
        $td_units = $td[2];

        # add trend data name values to list, however skip duplicate names
        unless (exists $td{$td_name}) {
          $td_name .= $td_name . ","; 
          $td_vals .= $td_val . ","; 
          $td{$td_name} = 1;
        }
        next;
      }

    } 

    # no dashes in values
    chop $td_list;

    chop $td_vals;
    chop $td_name;
    chop $nl;
    # put together the result line or record
      if ($mn ne "") {
        $resrecord = qq($date,$time,$edate,$etime,$tn,$job_id,$mn,$sn,$nn,$nc,"$pl",$results,$td_vals,"$nl"\n);
        $hdr = qq(date,time,EndDate,EndTime,TestName,JobId,MachineName,SegmentName,NumNodes,NumCores,ParamList,Results,$td_name,NodeList\n);
      } else{
        $resrecord = qq($date,$time,$edate,$etime,$tn,$job_id,$sn,$nn,$nc,"$pl",$results,$td_vals,"$nl"\n);
        $hdr = qq(date,time,EndDate,EndTime,TestName,JobId,SegmentName,NumNodes,NumCores,ParamList,Results,$td_name,NodeList\n);
      }

    # create handle where to place results in csv format  
    my $of = $tn . "_results.csv";
    open( OFILE, ">>$ofd/$of") or die "$prog: Failed to open $tn target data csv file, $!\n";
    print OFILE $resrecord;
    close( OFILE );
    # header file lines should correspond one for one with data lines, thus catenation
    my $hof = $tn . "_header.csv";
    open( HFILE, ">>$ofd/$hof") or die "$prog: Failed to open $tn target header csv file, $!\n";
    print HFILE $hdr;
    close( HFILE );
    close( LOG );

exit (0);

sub usage {

  print "\n\n";
  print <<usage_info;
usage: $prog [options] <log dir> 
          -d print debugging info 
          -h print this help screen
usage_info
  print "\n\n";
}

