#!/bin/bash

if [ -z $1 ]; then
    DEST=spack
else
    DEST=$1/spack
fi

echo $DEST

git clone "https://github.com/spack/spack.git" "$DEST"
cd $DEST || exit
git checkout tags/v0.15.4

# We have to install something to initialize the db. Patchelf is small
# and often needed anyway.
. share/spack/setup-env.sh
spack install patchelf
