import sys
from argparse import ArgumentParser
from pathlib import Path
from collections import defaultdict
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from typing import TextIO, Dict, Tuple, List


def main() -> int:
    parser = _setup_parser()
    args = parser.parse_args()

    lockfiles = [f for p in args.lockfiles for f in Path().glob(p)]

    if len(lockfiles) < 2:
        print("check_inconsistent_deps expects at least two lockfiles, but only "
              " {len(args.lockfiles)} was/were provided.",file=sys.stderr)

        sys.exit(1)

    dependency_groups = {}

    for lockfile in lockfiles:
        try:
            with lockfile.open("r", encoding="utf-8") as fin:
                dependency_groups[str(lockfile)] = dependency_groups.append(_parse_lockfile(lockfile))
        except (OSError, ValueError) as err:
            print(f"Error reading lockfile at {lockfile}: {err}")

            sys.exit(2)

    merged_groups = _merge_dependency_groups(dependency_groups)
    inconsts = _get_package_inconsistencies(merged_groups)

    if len(inconsts) > 0:
        _print_package_inconsistencies(inconsts, errfile=sys.stderr)

        # We'll still give return code 0 here, since we just want to warn, not fail completely.
    else:
        print("No package inconsistencies found between environments.")

    sys.exit(0)

def _get_package_inconsistencies(merged_groups: Dict[str, List[Tuple[str, str]]]) -> Dict[str, List[Tuple[str, str]]]:
    """Given a dictionary mapping package names to lists of tuples, each tuple of which pairs
    a specific lockfile with a version of that package, construct a new dictionary of the same
    structure containing only those packages for which inconsistencies exist."""

    result = {}

    for package, tuples in merged_groups.items():
        uniq_vers = _unique_versions(tuples)

        if len(uniq_vers) > 1:
            result[package] = uniq_vers

    return result

def _unique_versions(tuples: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
    """Given a list of tuples pairing lockfile paths with package versions, construct a new list
    of tuples such that no version appears more than once in the list."""

    res = []

    for pair in tuples:
        seen = False

        for uniq_pair in res:
            if pair[1] == uniq_pair[1]:
                seen = True
                break

        if not seen:
            res.append(pair)

    return res

def _merge_dependency_groups(dep_groups: Dict[str, Dict[str, str]]) -> Dict[str, List[Tuple[str, str]]]:
    """Combine two or more dictionaries, such that when the dictionaries have shared keys, the
    resultant dictionary has a list of the original dictionaries' values under that key."""

    result = defaultdict(list)

    for lockfile, dep_group in dep_groups.items():
        for key, val in d.items():
            result[key].append((lockfile, val))

    return result

def _parse_lockfile(lockfile: TextIO) -> Dict[str, str]:
    """Parse the requirements out of a lockfile, assuming the format generated by `piptools compile`
    and return a dictionary of dependencies mapping package names to versions."""

    for line in lockfile.lines():
        if line.strip().startswith(("#", "-")):
            continue

        req = Requirement(line.strip())

        if len(req.specifier) != 1:
            raise ValueError(
                f"Expected exactly one pinned specifier, got: {line.strip()}"
            )

        spec = next(iter(req.specifier))

        if spec.operator != "==":
            raise ValueError(
                f"Expected a '==' pin, got: {line.strip()}"
            )

        name = canonicalize_name(req.name)
        requirements[name] = spec.version

    return requirements

YELLOW = "\033[33m"
RESET = "\033[0m"

def _print_package_inconsistencies(pkg_inconsts: Dict[str, List[Tuple[str, str]]], errfile) -> None:
    """Print out any inconsistent package found."""

    print("Found the following inconsistent packages between environments:\n\n", file=errfile)

    for pkg, tuples in pkg_inconsts.items():
        print(f"{YELLOW}\tPackage: {pkg}\n\n{RESET}", file=errfile)

        for lockfile, version in tuples:
            print(f"{YELLOW}Lockfile {lockfile} requires version {version}.\n{RESET}", file=errfile)

        print("\n", file=errfile)

def _setup_parser() -> ArgumentParser:
    """Configure the arguments for the parser."""

    parser = ArgumentParser(
                    description="Checks for inconsistent dependencies between two or more "
                                "lockfiles.")
    parser.add_argument("lockfiles", nargs='*',
                        help="The paths to the lockfiles to compare against one another. These may "
                             "be globs.")

    return parser

if __name__ == "__main__":
    main()