name: Generate unit test coverage report

on:
  schedule:
    # Run at midnight on the first of the month
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      timeout:
        description: "Timeout value (in seconds) for Pavilion unit tests"
        required: true
        default: 300
        type: number
      lock_lifetime:
        description: "Lifetime (in seconds) after which a lock may be 'stolen' by other processes"
        required: true
        default: 300
        type: number

permissions:
  contents: read

jobs:
  coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v6

    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt
        pip install "coverage>=7.10"

    - name: Setup Pavilion application-level config
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml

    - name: Setup Spack
      run: |
        ./test/utils/spack_setup test

    - name: Run unit tests under coverage.py
      env:
        # coverage.py causes unit tests to run several times slower, so we need to increase the timeout
        PAV_UNITTEST_UNIVERSAL_TIMEOUT: ${{ inputs.timeout || 300}}
        PAV_UNITTEST_LOCK_LIFETIME: ${{ inputs.lock_lifetime || 300}}
      run: |
        echo "PAV_UNITTEST_UNIVERSAL_TIMEOUT: $PAV_UNITTEST_UNIVERSAL_TIMEOUT"
        echo "PAV_UNITTEST_LOCK_LIFETIME: $PAV_UNITTEST_LOCK_LIFETIME"
        sudo -E su $USER -c "PATH=$PATH; python -m coverage run ./test/run_tests --skip style --skip docs"

    - name: Combine data and generate report
      if: always()
      run: |
        python -m coverage combine
        python -m coverage report
        python -m coverage xml
        python -m coverage html

    - name: Upload XML coverage report
      uses: actions/upload-artifact@v6
      with:
        name: coverage-xml
        path: coverage.xml

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v6
      with:
        name: coverage-html
        path: htmlcov