name: Run demo tests

on:
  push:
    branches:
      - develop
      - stable
  pull_request:
    branches:
      - develop
      - stable

jobs:
  demo_runs:
    # Check to make sure Pavilion can auto-fetch it's dependencies.
    name: Run demo tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: sudo apt install gcc

    - name: Ensure all tests pass
      run: |
        source examples/demo/activate.sh
        pav run -v QUIET demo advanced buildit
        pav wait
        pav results --all-passed
