name: demo_configs

on:
  push:
    branches: [ develop  ]
  pull_request:
    branches: [ develop ]

jobs:
  demo_runs:
    # Check to make sure Pavilion can auto-fetch it's dependencies.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: install-deps
      run: sudo apt install gcc

    - name:
      run: |
        source examples/demo/activate.sh
        pav run -v QUIET demo advanced buildit
        pav wait
        pav results --all-passed
