name: demo_configs

on:
  push:
    branches:
      - develop
      - stable
  pull_request:
    branches:
      - develop
      - stable

permissions:
  contents: read

jobs:
  demo_runs:
    # Check to make sure Pavilion can auto-fetch it's dependencies.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        pip install -r requirements/base-py310-lock.txt
        pip install -r requirements/test-py310-lock.txt
        pip install -r requirements/docs-py310-lock.txt

    - name: Install GCC
      run: sudo apt install gcc

    - name: Run demo tests
      run: |
        source examples/demo/activate.sh
        pav run -v QUIET demo advanced buildit
        pav wait
        pav results --all-passed
