name: demo_configs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  demo_runs:
    # Check to make sure Pavilion can auto-fetch it's dependencies.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: install-deps
      run: sudo apt install gcc

    - name: 
      run: |
        . examples/demo/activate.sh
        ls -l examples/demo/tests
        pav show tests
        pav run -v QUIET demo advanced buildit
        pav wait 
        pav results --all-passed
