name: Open stable -> develop PR after push to stable

on:
  push:
    branches: [stable]

permissions:
  contents: read
  pull-requests: write

jobs:
  open-sync-pr:
    runs-on: ubuntu-latest

    env:
      BASE_BRANCH: ${{ github.event.repository.default_branch }}
      HEAD_BRANCH: stable
      TEMP_BRANCH: ci/sync-stable-to-develop

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.HEAD_BRANCH }}
          fetch-depth: 0

      - name: Fetch ${{ env.BASE_BRANCH }}
        run: git fetch origin ${{ env.BASE_BRANCH }}:${{env.BASE_BRANCH}}

      - name: Rebase temporary branch onto ${{ env.BASE_BRANCH }}
        run: |
          git switch -c ${{ env.TEMP_BRANCH }}
          git rebase origin/${{ env.BASE_BRANCH }}

      - name: Create pull request from ${{ env.HEAD_BRANCH }} to ${{ env.BASE_BRANCH }}
        uses: peter-evans/create-pull-request@v8
        with:
          base: ${{ env.BASE_BRANCH }}
          branch: ${{ env.TEMP_BRANCH }}
          commit-message: "Sync `${{ env.HEAD_BRANCH}}` into `${{ env.BASE_BRANCH }}`"
          title: "Sync `${{ env.HEAD_BRANCH }}` into `${{ env.BASE_BRANCH}}`"
          body: |
            **This PR was generated automatically by the `sync-stable` workflow because changes
            were pushed to the `${{ env.HEAD_BRANCH }}` branch. Please review if carefully.**

            This PR merges the latest changes from `${{ env.HEAD_BRANCH }}` into `${{ env.BASE_BRANCH }}`

          delete-branch: true