name: Run Pavilion unit tests

on:
  push:
    branches:
      - develop
      - stable
  pull_request:
    branches:
      - develop
      - stable

permissions:
  contents: read

jobs:
  load-python-versions:
    name: Load Python versions
    runs-on: ubuntu-latest

    outputs:
      supported_py_versions: ${{ steps.load-py-versions.outputs.supported_py_versions }}
      legacy_py_versions: ${{ steps.load-py-versions.outputs.legacy_py_versions }}
      default_py_version: ${{ steps.load-py-versions.outputs.default_py_version }}

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6

      - name: Load Python version matrix
        id: load-py-versions
        run: |
          echo "supported_py_versions=$(jq -c '.supported_py_versions' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          echo "legacy_py_versions=$(jq -c '.legacy_py_versions' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          echo "default_py_version=$(jq -c '.default_py_version' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  style:
    name: Run style checks
    runs-on: ${{ fromJson(needs.load-python-versions.outputs.default_py_version).os }}
    needs: load-python-versions

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6

      - name: Setup Python ${{ fromJson(needs.load-python-versions.outputs.default_py_version).python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ fromJson(needs.load-python-versions.outputs.default_py_version).python }}

      - name: Install dependencies
        run: pip install -r test/requirements.txt

      - name: Run style tests
        run: ./test/run_tests -q -o style -o debug_prints

  docs:
    name: Run documentation checks
    runs-on: ${{ fromJson(needs.load-python-versions.outputs.default_py_version).os }}
    needs: load-python-versions

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6

      - name: Setup Python ${{ fromJson(needs.load-python-versions.outputs.default_py_version).python }}
        uses: actions/setup-python@v6
        with:
          python-version: "${{ fromJson(needs.load-python-versions.outputs.default_py_version).python }}"

      - name: Install dependencies
        run: |
          pip install -r test/requirements.txt
          pip install -r docs/requirements.txt

      - name: Run documentation tests
        run: ./test/run_tests -o 'doc*' -q

  unittests-modern-python:
    name: Run unit tests on Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    needs:
        - load-python-versions
        - style
        - docs

    strategy:
      matrix:
        include: ${{ fromJson(needs.load-python-versions.outputs.supported_py_versions) }}

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python }}"

      - name: Install dependencies
        run: |
            pip install -r test/requirements.txt
            pip install -r docs/requirements.txt

      - name: Setup Spack
        run: ./test/utils/spack_setup test

      - name: Run unit tests
        run: ./test/run_tests

      - name: Zip output directory
        if: failure()
        run: |
          # If we don't zip this ourselves, it will run infinitely due to symlink loops.
          cd test
          ./utils/make_symlinks_relative output
          zip -yr output.zip output

      - name: Upload output directory
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: output_py${{ matrix.python }}
          path: test/output.zip

  unittests-legacy-python:
    # We run this as a separate job because older versions of Python which are no longer supported
    # by GitHub, for the `setup-python` action, will still work in containers.
    name: Run unit tests on Python ${{ matrix.python }} (containerized)
    runs-on: ${{ matrix.os }}
    container: python:${{ matrix.python }}
    needs:
      - load-python-versions
      - style
      - docs

    strategy:
      matrix:
        include: ${{ fromJson(needs.load-python-versions.outputs.legacy_py_versions) }}

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
            pip install -r test/requirements.txt
            pip install -r docs/requirements.txt

      - name: Create bash symlink at /usr/bin/bash
        # This is necessary because Pavilion's default shebang is /usr/bin/bash
        run: test -e /usr/bin/bash || ln -s /bin/bash /usr/bin/bash

      - name: Setup Spack
        run: ./test/utils/spack_setup test

      - name: Run unit tests
        run: ./test/run_tests

      - name: Install zip
        if: failure()
        run: |
          apt-get update
          apt-get install -y zip

      - name: Zip output directory
        if: failure()
        run: |
          # If we don't zip this ourselves, it will run infinitely due to symlink loops.
          cd test
          ./utils/make_symlinks_relative output
          zip -yr output.zip output

      - name: Upload output directory
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: output_py${{ matrix.python }}
          path: test/output.zip