name: Run unit tests

on:
  push:
    branches:
      - develop
      - stable
  pull_request:
    branches:
      - develop
      - stable

jobs:
  # The debug job is meant for debugging CI related issues.
  debug:
    name: Debug CI-related issues
    # Comment out the following line to enable.
    if: ${{ false }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: setup
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        #echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        #./test/utils/spack_setup test

    - name: Run unit tests
      run: |
        ./test/run_tests

    - name: Zip working directory
      if: always()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative working_dir
        zip -yr working_dir.zip working_dir

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test_output
        path: test/working_dir.zip

  style:
    name: Run Python style checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: Set up Pavilion application-level config
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml

    - name: Run style tests
      run: |
        sudo -E su $USER -c "PATH=$PATH; ./test/run_tests -q -o style -o debug_prints"

  docs:
    name: Run documentation checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: Set up Pavilion application-level config
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml

    - name: Run documentation tests
      run: ./test/run_tests -o 'doc*' -q

  unittests-python-36:
    # We run this as a separate job because Python 3.6 is no longer supported by GitHub, for the
    # `setup-python` action, but it will still work in a container
    name: Run unit tests on Python 3.6 (containerized)
    runs-on: ubuntu-latest
    container: python:3.6
    needs:
    - style
    - docs

    steps:
    - name: Make sure bash exists where Pavilion expects it
      run: |
        /bin/bash --version

    - name: Check Python version
      run: |
        PY_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        test "$PY_VERSION" = 3.6

    - name: Checkout Pavilion repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt
        sphinx-build --version
        pylint --version

    - name: Set up Pavilion application-level config
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test

    - name: Run unit tests
      run: |
        ./test/run_tests

    - name: Install zip
      if: failure()
      run: |
        apt-get update
        apt-get install -y zip

    - name: Zip working directory
      if: failure()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative working_dir
        zip -yr working_dir.zip working_dir

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_output_3.6
        path: test/working_dir.zip

  unittests-modern-python:
    name: Run unit tests on Python ${{ matrix.environment.python }}
    runs-on: ${{ matrix.environment.os }}
    needs:
        - style
        - docs

    strategy:
      matrix:
        environment:
          - python: "3.7"
            os: ubuntu-22.04 # This is the latest version that supports Python 3.7
          - python: "3.10"
            os: ubuntu-latest
          - python: "3.12"
            os: ubuntu-latest

    steps:
    - name: Checkout Pavilion repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.environment.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.environment.python }}
    - name: Check Python version
      run: |
        PY_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        test "$PY_VERSION" = "${{ matrix.environment.python }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt
        sphinx-build --version
        pylint --version

    - name: Set up Pavilion application-level config
      run: |
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test

    - name: Run unit tests
      run: |
        ./test/run_tests

    - name: Zip working directory
      if: failure()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative working_dir
        zip -yr working_dir.zip working_dir

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_output_${{ matrix.environment.python }}
        path: test/working_dir.zip
