name: unittests

on:
  push:
    branches:
      - develop
      - stable
  pull_request:
    branches:
      - develop
      - stable

jobs:
  # The debug job is meant for debugging CI related issues.
  debug:
    # Comment out the following line to enable.
    if: ${{ false }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    # Set run_tests to run only the specific tests you need to fix.
    - name: run_tests
      run: ./test/run_tests

    - name: zip_output_dir
      if: always()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative output
        zip -yr test_output.zip output

    - name: logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test_output
        path: test/test_output.zip

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: run_tests
      run: ./test/run_tests -q -o style -o debug_prints"

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: run_tests
      run: ./test/run_tests -o 'doc*' -q

  unittests-3_7:
    runs-on: ubuntu-22.04
    needs:
        - style
        - docs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt
        sphinx-build --version
        pylint --version

    - name: Set up Spack
      run: ./test/utils/spack_setup test

    - name: run_tests
      run: ./test/run_tests

    - name: zip_output_dir
      if: failure()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative output
        zip -yr test_output.zip output

    - name: logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_output_3.7
        path: test/test_output.zip

  unittests-3_10:
    runs-on: ubuntu-latest
    needs:
        - style
        - docs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: Set up Spack
      run: ./test/utils/spack_setup test

    - name: run_tests
      run: ./test/run_tests"

    - name: zip_output_dir
      if: failure()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative output
        zip -yr test_output.zip output

    - name: logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_output_3.10
        path: test/test_output.zip

  unittests-3_12:
    runs-on: ubuntu-latest
    needs:
        - style
        - docs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        pip install -r docs/requirements.txt

    - name: Set up Spack
      run: ./test/utils/spack_setup test

    - name: run_tests
      run: ./test/run_tests"

    - name: zip_output_dir
      if: failure()
      run: |
        # If we don't zip this ourselves, it will run infinitely due to
        # symlink loops.
        cd test
        ./utils/make_symlinks_relative output
        zip -yr test_output.zip output

    - name: logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_output_3.12
        path: test/test_output.zip