name: Update Python dependencies

on:
  # The on.push trigger is present only for ease of testing. It should be removed before this
  # workflow is merged into develop.
  push:
    branches:
      - 'hwikle/offline-release-ci'
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Branch against which to open the PR"
        required: false
        default: ""
        type: string

permissions:
  contents: write
  pull-requests: write

env:
  # BASE_BRANCH: ${{ inputs.base_branch != '' && inputs.base_branch || github.event.repository.default_branch }}
  # This default is present only for ease of testing. It should be removed and replaced with the above line
  # before this workflow is merged into develop.
  BASE_BRANCH: ${{ inputs.base_branch != '' && inputs.base_branch || 'hwikle/offline-release-ci' }}
  DEPENDENCY_TYPES: base test docs dev

jobs:
  load-python-versions:
    name: Load Python versions
    runs-on: ubuntu-latest

    outputs:
      supported_py_versions: ${{ steps.load-py-versions.outputs.supported_py_versions }}
      legacy_py_versions: ${{ steps.load-py-versions.outputs.legacy_py_versions }}
      default_py_version: ${{steps.load-py-versions.outputs.default_py_version}}

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v4

      - name: Load Python version matrix
        id: load-py-versions
        run: |
          echo "supported_py_versions=$(jq -c '.supported_py_versions' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          echo "legacy_py_versions=$(jq -c '.legacy_py_versions' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          echo "default_py_version=$(jq -c '.default_py_version' .github/py-versions.json)" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  update-lockfiles-modern-python:
    name: Regenerate lockfiles for Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    needs: load-python-versions

    strategy:
      matrix:
        include: ${{ fromJson(needs.load-python-versions.outputs.supported_py_versions) }}

    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Compute py_tag
        id: py_tag
        shell: bash
        run: |
          PY_TAG="py${{ matrix.python }}"
          PY_TAG="${PY_TAG/./}"
          echo "py_tag=${PY_TAG}" >> "$GITHUB_OUTPUT"

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip pip-tools

      - name: Regenerate lockfiles
        # There's a possibility of inconsistencies here between the test and runtime environments
        # if each requires a different version of the same transitive dependency. It's unlikely,
        # but we should think about using a tool like Poetry that supports a single lockfile
        # with multiple dependency groups.
        run: |
          for dep_type in $DEPENDENCY_TYPES; do
            python -m piptools compile \
              --upgrade \
              --generate-hashes \
              --no-strip-extras \
              --output-file "requirements/${dep_type}-${{ steps.py_tag.outputs.py_tag }}-lock.txt" \
              requirements/${dep_type}.in
          done

      - name: Install dependencies for check_inconsistent_deps.py
        run:
          python -m pip install packaging

      - name: Check for inconsistencies between environments
        # For now we'll just issue a warning, and not fail, if inconsistencies are found.
        run: |
          python .github/utils/check_inconsistent_deps.py "requirements/*-${{ steps.py_tag.outputs.py_tag }}-lock.txt"

      - name: Upload generated lockfiles
        uses: actions/upload-artifact@v4
        with:
          name: lockfiles-${{ steps.py_tag.outputs.py_tag }}
          path: requirements/*-${{ steps.py_tag.outputs.py_tag}}-lock.txt

  update-lockfiles-legacy-python:
    name: Regenerate lockfiles for Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    container: python:${{ matrix.python }}
    needs: load-python-versions

    strategy:
      matrix:
        include: ${{ fromJson(needs.load-python-versions.outputs.legacy_py_versions) }}

    steps:
      - name: Checkout Pavilion repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip pip-tools

      - name: Compute py_tag
        id: py_tag
        shell: bash
        run: |
          PY_TAG="py${{ matrix.python }}"
          PY_TAG="${PY_TAG/./}"
          echo "py_tag=${PY_TAG}" >> "$GITHUB_OUTPUT"

      - name: Regenerate lockfiles
        # There's a possibility of inconsistencies here between the test and runtime environments
        # if each requires a different version of the same transitive dependency. It's unlikely,
        # but we should think about using a tool like Poetry that supports a single lockfile
        # with multiple dependency groups.
        run: |
          for dep_type in $DEPENDENCY_TYPES; do
            python -m piptools compile \
              --upgrade \
              --generate-hashes \
              --output-file "requirements/${dep_type}-${{ steps.py_tag.outputs.py_tag }}-lock.txt" \
              "requirements/${dep_type}.in"
          done

      - name: Install dependencies for check_inconsistent_deps.py
        run:
          python -m pip install packaging

      - name: Check for inconsistencies between environments
        # For now we'll just issue a warning, and not fail, if inconsistencies are found.
        run: |
          python .github/utils/check_inconsistent_deps.py "requirements/*-${{ steps.py_tag.outputs.py_tag }}-lock.txt"

      - name: Upload generated lockfiles
        uses: actions/upload-artifact@v4
        with:
          name: lockfiles-${{ steps.py_tag.outputs.py_tag }}
          path: requirements/*-${{ steps.py_tag.outputs.py_tag }}-lock.txt

  create-pr:
    name: Commit updated lockfiles and open PR
    runs-on: ubuntu-latest
    needs:
      - update-lockfiles-modern-python
      - update-lockfiles-legacy-python

    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Remove old lockfiles
        run: |
          git rm requirements/*-py*-lock.txt
          git status

      - name: Download lockfiles
        uses: actions/download-artifact@v4
        with:
          pattern: lockfiles-py*
          path: requirements
          merge-multiple: true

      - name: Stage new lockfiles
        run: |
          git add requirements/*-py*-lock.txt
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ env.BASE_BRANCH }}
          branch: ci/update-python-dependencies
          commit-message: "Update Python dependency lockfiles"
          title: "Update Python dependency lockfiles"
          body: |
            This PR regenerates the Python dependency lockfiles from:

            - `requirements/base.in`
            - `requirements/test.in`
            - `requirements/docs.in`
            - `requirements/dev.in`

            Updated files:
            - `requirements/base-py36-lock.txt`
            - `requirements/base-py310-lock.txt`
            - `requirements/base-py312-lock.txt`
            - `requirements/test-py36-lock.txt`
            - `requirements/test-py310-lock.txt`
            - `requirements/test-py312-lock.txt`
            - `requirements/docs-py36-lock.txt`
            - `requirements/docs-py310-lock.txt`
            - `requirements/docs-py312-lock.txt`
            - `requirements/dev-py36-lock.txt`
            - `requirements/dev-py310-lock.txt`
            - `requirements/dev-py312-lock

            These lockfiles are generated automatically with `pip-compile --upgrade --generate-hashes`.
          delete-branch: true